default: &default
  adapter: postgresql
  encoding: unicode
  # Sidekiq
  pool: 10
  # Default setting
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i %>

development:
  <<: *default
  database: caten_church_dev
  username: Xin
  password:

test:
  <<: *default
  database: caten_church_test
  username: Xin
  password:

production:
  <<: *default
  password:
