default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: caten_church_dev
  username: caten_church
  password:

test:
  <<: *default
  database: caten_church_test
  username: caten_church
  password:

production:
  <<: *default
  url: <%= Rails.application.credentials[:production].fetch(:database_url) { ENV[:DATABASE_URL] } %>
